@startuml ECS
title ECS服务架构
!include C4_Dynamic.puml
!include C4_Code.puml
!include Lua.puml

AddRelTag("redirect",$lineColor="blue",$techn="redirect")
AddRelTag("opt",$lineColor="Gray",$lineStyle=DashedLine(), $techn="可能会")
Component(core, "SkynetCore", "C")

LService_Boundary(scene, "Scene"){
    LList(systems,"Systems")
    LObject(entitys,"Entitys","作为内存数据存在")
    LTable(messages,"Messages")
}

Component(war, "War", "Lua")
Component(gate, "Gated", "Lua")
Component(agent, "Agent", "Lua")
Person(user, "User")




Rel_U(user, gate, "request")
Rel_U(gate, agent, "client","rawcall")
Rel(agent, gate, "返回")
Rel_L(agent, war, "战斗消息","redirect",$tags="redirect")
Rel_R(war, gate, "返回",$tags="redirect")
Rel_L(agent, messages, "场景消息","redirect",$tags="redirect")
Rel(messages, gate, "返回",$tags="redirect")

Rel_Neighbor(messages, entitys, "modify",$tags="opt")
Rel_U(core, systems, "drive","timeout")
Rel_R(entitys, systems,"read only")
@enduml
