@startuml GameSever
title GameServer
header Loginserver and GameServer on a Node
skinparam DefaultFontName WenQuanYi Zen Hei
skinparam DefaultMonospacedFontName UbuntuMono-R
!include C4_Component.puml
!include C4_Dynamic.puml
Person(user, "User")
ContainerDb(gameDb, "GameDB", "Mongodb")
Container(loginServer, "LoginServer", "Skynet","Auth and notify gameserver")
Container_Boundary(gameServer, "GameServer"){
    Component(gated, "Gated", "Lua","Manage connections, notify loginserver when kicked and logout")
    Component(agent, "Agent", "Lua","Handle most of user requests and return a string to gated, or need communite with other service")
    Component(world, "World", "Lua","Make scene from maps, save all remote secene services, maintenance all player scene info")
    Component(scene, "Scene", "Lua","Manage all entitys(NPC, Player, Item, Event, ...)")
}

Rel_R(gated,loginServer,"Register")
Rel(world,scene,"Newservice")
Rel_L(loginServer, gated,"Notify uid, secret","login")
Rel_U(gated, agent,"New","login")
Rel_D(gameDb, agent,"Load player data")
Rel_U(user, gated,"Connect Handshake Request","TCP")
Rel_U(gated, agent,"Request","rawcall")
Rel_L(agent,world,"Query map scene info","call")
Rel_D(agent,scene,"Enter scene")
Rel_Neighbor(gated,loginServer,"logout")
@enduml