@startuml Test
!include core.puml
!include Skynet.puml

title Service Gated

' left to right direction
Service(agent,"Agent","玩家代理")
Service(core,"Skynet Core")
Service_Boundary(gateservice,"网关服务") {
    Module_Boundary(gated,"Gated") {
        Table(handlers,"Handlers", "login_handler logout_handler kick_handler disconnect_handler request_handler register_handler")
    }
    Module_Boundary(gateserver,"GateServer") {
        Table(socketevhandler,"sockethandler","data\nmore\nopen\nclose\nerror\nwarning")
        Table(gscmd,"cmd","open\nclose")
        Table(gsfun,"functions","openclient\ncloseclient")
    }

    Module_Boundary(msgserver,"MsgServer") {
        Table(msgcmd,"cmd","cmd handler from the gated handlers")
        Table(msghandler,"msghandler","open\nconnect\ncommand\ndisconnect\nerror\nmessage")
        Table(msgfun,"functions")
        Fun(auth,"auth")
        Fun(request,"request")
        Rel_L(msghandler, auth, "receive message of handshake")
        Rel_Neighbor(msghandler, request, "receive message of data")
    }

}

Rel_U(core, socketevhandler, "socket message(with subcmd)")
Rel_U(socketevhandler, msghandler, "socket message")
Rel_U(request, handlers, "call request_handler")
Rel_U(handlers, agent, "call","skynet.rawcall")
Rel_U(core, gscmd, "open/close socket server")
Rel_U(core, msgcmd, "login/logout/kick")
Rel_U(msgcmd, handlers, "call","login/logout/kick")
@enduml