@startuml Gateserver
!include C4_Component.puml
Person(user, "User")
Container_Boundary(skynet, "Skynet"){
    Component(ss, "SocketServer", "C")
    Component(gateserver, "Gateserver", "Lua")
    Component(agent, "Agent", "Lua")
}
Rel_U(user, ss, "TCP")
Rel(ss, gateserver, "netpack.filter，这里会进行分包，2字节头")
Rel(gateserver, agent, "msg,sz")
Rel(agent, ss, "write data，不走netpack，直接 string.pack")
@enduml