@startuml Test
!include core.puml
!include Skynet.puml
title Service Gated

' left to right direction
Service(agent,"Agent")
Service(core,"Skynet Core")
Service_Boundary(gateservice,"网关服务") {
    Module(gated,"Gated") {
        Table(handlers,"Handlers", "login_handler logout_handler kick_handler disconnect_handler request_handler register_handler")
    }
    Module(gateserver,"GateServer") {
        Table(socketevhandler,"SocketEventHandler","data more open close error warning")
        Table(gscmd,"CMD","open close")
        Table(gsfun,"Functions","openclient closeclient")
    }

    Module(msgserver,"MsgServer") {
        Table(msgcmd,"CMD","cmd handler from the gated handlers")
        Table(msghandler,"MsgHandler","open connect command disconnect error message")
        Fun(auth,"Auth")
        Fun(request,"Request")
        Table(msgfun,"Functions")
        Rel(msghandler, auth, "receive message of handshake")
        Rel(msghandler, request, "receive message of data")
    }

}

Rel(core, socketevhandler, "socket message(with subcmd)")
Rel(socketevhandler, msghandler, "socket message")
Rel(request, handlers, "call request_handler")
Rel(handlers, agent, "call","skynet.rawcall")
Rel(core, gscmd, "open/close socket server")
Rel(core, msgcmd, "login/logout/kick")
Rel(msgcmd, handlers, "call","login/logout/kick")
@enduml