@startuml Logind
!include Skynet.puml
!include C4_Dynamic.puml
Person(user, "User")
Container_Boundary(skynet, "Skynet"){
Service(ss,"SocketServer")
Service_Boundary(master, "Master"){
    Fun(accept,"Accept")

}
Table(conf,"Conf", "auth_handler login_handler")
Service_Boundary(slave,"Slave") {

}
}

Rel_U(user, ss, "TCP")
Rel_U(ss, accept,"callback")
Rel_L(accept, slave, "dispatch to slave to auth","call")
Rel_U(slave, conf, "call auth_handler")
Rel_U(accept,conf,"call login_handler")
@enduml