@startuml Arch
title 整体架构
!include C4_Container.puml
Person(user, "User","Android, iOS, Web, WeChat")
System_Boundary(arch, "Arch"){
    Container(login, "LoginNode", "skynet","账号注册、账号登录")
    Container(game, "GameNode", "skynet","游戏世界")
    ContainerDb(accdb, "AccountDB", "mongodb")
    ContainerDb(gamedb, "GameDB", "mongodb")
    ContainerDb(logdb, "LogDB", "mysql")
}
Rel_U(user, login, "注册、登录","TCP,Line base")
Rel_U(user, game, "游戏","TCP,line base handshake, protobuf request")
Rel_Neighbor(login, game, "上线通知","skynet.cluster.call")
Rel_U(login, accdb, "使用")
Rel_U(game, gamedb, "使用")
Rel_U(game, logdb, "使用")

@enduml