@startuml Logind
!include Lua.puml
!include C4_Dynamic.puml
Person(user, "User")
Container(gamenode, "GameNode", "Skynet")
Container_Boundary(skynet, "Skynet"){
    LService(db,"Account DB","","MongoDB")
    LService(ss,"SocketServer","C")
    LService_Boundary(master, "Master"){
        LFunction(login_handler,"login_handler")
        LFunction(accept,"Accept")
    }
    LService_Boundary(slave,"Slaves") {
            LFunction(auth_handler,"auth_handler")
    }
}


Rel_U(user, ss, "TCP")
Rel_U(ss, accept,"callback")
Rel_U(accept, auth_handler, "dispatch to slave to auth","call")
Rel_U(auth_handler, db, "Query")
Rel_L(accept,login_handler,"call login_handler")
Rel_R(login_handler, gamenode, "notify")
@enduml
